### ISSUE TITLE
【样式问题】FAQs 展开后下方的 “Build your landing page, show your product, and start earning!”的红框错位了

### ISSUE THREAD

**Issue by ayonliu** [weijunext/landing-page-boilerplate#3]
正常情况：
![image](https://github.com/weijunext/landing-page-boilerplate/assets/1035056/4faf1681-f4de-48f7-8b8c-f6332bf69d84)

FAQs 中的条目展开后的错位效果：
![image](https://github.com/weijunext/landing-page-boilerplate/assets/1035056/33281ff7-467c-4533-b551-47d58a55434d)

**Comment by weijunext** [comment]
Done!
