### ISSUE TITLE
sudo npm install 失败了，有大佬遇到过么

### ISSUE THREAD

**Issue by ice45571** [weijunext/landing-page-boilerplate#6]
<img width="945" alt="image" src="https://github.com/weijunext/landing-page-boilerplate/assets/21982940/ef06eeaf-5160-464d-a427-1d321dc1c5f2">

**Comment by ice45571** [comment]
npm ERR! code E400
npm ERR! 400 Bad Request - GET https://registry.npmmirror.com/which-typed-array/-/which-typed-array-1.1.13.tgz

npm ERR! A complete log of this run can be found in: /usr/local/cache/npm/_logs/2024-04-16T09_12_12_616Z-debug-0.log

**Comment by weijunext** [comment]
用yarn或者pnpm尝试一下

**Comment by ice45571** [comment]
> 用yarn或者pnpm尝试一下

谢谢，昨天npm试了也不行，今天再试下就ok了
